// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackCare.Infrastructure.Persistence;

#nullable disable

namespace TrackCare.Infrastructure.Migrations
{
    [DbContext(typeof(TrackCareDbContext))]
    [Migration("20260525110753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackCare.Domain.Entities.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoCompleto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RecolhimentoId")
                        .HasColumnType("integer");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioUpload")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RecolhimentoId");

                    b.ToTable("anexos", (string)null);
                });

            modelBuilder.Entity("TrackCare.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecolhimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Setor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RecolhimentoId");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("TrackCare.Domain.Entities.HistoricoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RecolhimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("StatusNovo")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RecolhimentoId");

                    b.ToTable("historico_status", (string)null);
                });

            modelBuilder.Entity("TrackCare.Domain.Entities.Recolhimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClienteContato")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClienteEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ClientePlano")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteTelefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataColetaReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDevolucaoReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevistaColeta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevistaDevolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoProblema")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Hgid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("JaRecolhido")
                        .HasColumnType("boolean");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RelatorioN3")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TicketBlip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TicketHub")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteNome");

                    b.HasIndex("DataSolicitacao");

                    b.HasIndex("Hgid");

                    b.HasIndex("NumeroSerie");

                    b.HasIndex("Status");

                    b.ToTable("recolhimentos", (string)null);
                });

            modelBuilder.Entity("TrackCare.Domain.Entities.Anexo", b =>
                {
                    b.HasOne("TrackCare.Domain.Entities.Recolhimento", "Recolhimento")
                        .WithMany("Anexos")
                        .HasForeignKey("RecolhimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recolhimento");
                });

            modelBuilder.Entity("TrackCare.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("TrackCare.Domain.Entities.Recolhimento", "Recolhimento")
                        .WithMany("Comentarios")
                        .HasForeignKey("RecolhimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recolhimento");
                });

            modelBuilder.Entity("TrackCare.Domain.Entities.HistoricoStatus", b =>
                {
                    b.HasOne("TrackCare.Domain.Entities.Recolhimento", "Recolhimento")
                        .WithMany("HistoricoStatus")
                        .HasForeignKey("RecolhimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recolhimento");
                });

            modelBuilder.Entity("TrackCare.Domain.Entities.Recolhimento", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Comentarios");

                    b.Navigation("HistoricoStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
